#!/bin/bash

# Script to help deploy to Render
# This script provides the commands needed for deployment

echo "═══════════════════════════════════════════════════════════════"
echo "           Render Deployment Helper"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "This script will guide you through deploying to Render."
echo ""
echo "Prerequisites:"
echo "1. GitHub repository pushed (✅ Done)"
echo "2. Render account (sign up at https://render.com)"
echo ""
echo "Steps:"
echo ""
echo "1. Go to https://render.com and sign in"
echo "2. Click 'New' → 'PostgreSQL'"
echo "   - Name: order-execution-db"
echo "   - Plan: Free"
echo "   - Copy the Internal Database URL"
echo ""
echo "3. Click 'New' → 'Redis'"
echo "   - Name: order-execution-redis"
echo "   - Plan: Free"
echo "   - Copy the Internal Redis URL and password"
echo ""
echo "4. Click 'New' → 'Web Service'"
echo "   - Connect GitHub repository: aks-akanksha/order-execution-engine"
echo "   - Name: order-execution-engine"
echo "   - Environment: Node"
echo "   - Build Command: npm ci && npm run build"
echo "   - Start Command: node dist/index.js"
echo "   - Plan: Free"
echo ""
echo "5. Add Environment Variables:"
echo "   NODE_ENV=production"
echo "   PORT=3000"
echo "   DATABASE_URL=<from-postgres-step>"
echo "   REDIS_HOST=<from-redis-step>"
echo "   REDIS_PORT=6379"
echo "   REDIS_PASSWORD=<from-redis-step>"
echo "   QUEUE_CONCURRENCY=10"
echo "   ORDERS_PER_MINUTE=100"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "7. Wait for deployment (5-10 minutes)"
echo ""
echo "8. Once deployed, your URL will be:"
echo "   https://order-execution-engine.onrender.com"
echo ""
echo "═══════════════════════════════════════════════════════════════"

